### ISSUE TITLE
Ошибка авторизации

### ISSUE THREAD

**Issue by luarsoll** [GoodKitties/Export#1]
При попытке выкачать дневник выдает ошибку авторизации. Логин-пароль точно правильные (набирала несколько раз, плюс в браузере вылогинилась и залогинилась обратно). При этом два соо, от которых знаю пароли, выкачать удалось.
Видимая разница между дневником и соо:
- Логин дневника латиницей, логины соо - кириллицей
- Пароль от дневника содержит одинарную кавычку ', пароли от соо ее не содержат
- Дневник закрыт от незарегистрированных, сообщества открыты всем ветрам

Прошлая версия diary_exporter выкачивала и дневник и сообщества без проблем.

[diary_exporter_log_file.log](https://github.com/GoodKitties/Export/files/1511973/diary_exporter_log_file.log)

**Comment by dkalinina** [comment]
сообщество "Сидский стрит" теряет свое название при попадании в список сообществ. Это баг дайри и, возможно, наблюдается не только в этом конкретном случае.
Обработка подобных ситуаций добавлена в версии 2.0.3
