### ISSUE TITLE
Ошибка аутентификации

### ISSUE THREAD

**Issue by Nigrimmist** [GoodKitties/Export#2]
Не работает, пишет "Ошибка аутентификации". Win10. Кликнуть после этого ни на что нельзя. 

https://c2n.me/45LuL1k.png

**Comment by margilit** [comment]
Подтверждаю. Та же проблема: "Ошибка аутентификации". Пароли верны.

**Comment by KITSOlenaBorysova** [comment]
Та же ошибка, пробовала в виндоус10 и на маке

**Comment by Kaned1as** [comment]
@Nigrimmist, @margilit , @KITSOlenaBorysova нужен лог качалки. Должен лежать в папке выгрузки, с расширением "log"

**Comment by KITSOlenaBorysova** [comment]
[diary_exporter_log_file.log](https://github.com/GoodKitties/Export/files/4174040/diary_exporter_log_file.log)

**Comment by Kaned1as** [comment]
У вас качалка очень старой версии.
Скачайте новую по инструкции: https://github.com/GoodKitties/Export/tree/master/java
