### ISSUE TITLE
ошибка: could not find the main class

### ISSUE THREAD

**Issue by lordHenryW** [GoodKitties/Export#3]
программа не запускается. ошибка could not find the main class: 
![afc3c617-9408-4160-ac43-dcf314dc05bf](https://user-images.githubusercontent.com/60664780/73767942-3dbb5400-4789-11ea-8c29-c4973ae3fe6f.jpg)

**Comment by Kaned1as** [comment]
Скорее всего, джава старая. Вам нужна как минимум Java 8.
